module.exports = [
  {
    id: "1",
    team: "Tottenham Hotspur",
    league: "Premier League",
    name: "Camisa Titular 2024/25",
    price: 99.9,
    sizes: ["P", "M", "G", "GG"],
  },
  {
    id: "2",
    team: "Portugal",
    league: "Seleção",
    name: "Camisa Home 2024/25",
    price: 99.9,
    sizes: ["PP", "P", "M", "G", "GG", "XGG"],
  },
  {
    id: "3",
    team: "Wolfsburg",
    league: "Bundesliga",
    name: "Camisa Titular Azul",
    price: 99.9,
    sizes: ["P", "M", "G", "GG"],
  },
  {
    id: "4",
    team: "Inter de Milão",
    league: "Serie A",
    name: "Camisa Home 2024/25",
    price: 99.9,
    sizes: ["P", "M", "G", "GG", "XGG"],
  },
  {
    id: "5",
    team: "Agentina com detalhes dourados",
    league: "Serie A",
    name: "Camisa Home 2024/25",
    price: 99.9,
    sizes: ["P", "M", "G", "GG", "XGG"],
  },
  {
    id: "6",
    team: "Camisa Bahia 2023",
    league: "Serie A",
    name: "Camisa Home 2024/25",
    price: 99.9,
    sizes: ["P", "M", "G", "GG", "XGG"],
  },
  {
    id: "7",
    team: "Camisa do Barcelona 2023",
    league: "Serie A",
    name: "Camisa Home 2024/25",
    price: 99.9,
    sizes: ["P", "M", "G", "GG", "XGG"],
  },
  {
    id: "8",
    team: "Camisa da Argetina Azul",
    league: "Serie A",
    name: "Camisa Home 2024/25",
    price: 99.9,
    sizes: ["P", "M", "G", "GG", "XGG"],
  },
  {
    id: "8",
    team: "Camisa do Flamengo",
    league: "Serie A",
    name: "Camisa Home 2024/25",
    price: 99.9,
    sizes: ["P", "M", "G", "GG", "XGG"],
  },
];
